
import re                                         # Regex fuer die Hobby-Spalte
import pandas as pd                               # Einlesen und Umformen der Quelldaten
from pathlib import Path                          # plattformunabhaengige Pfade
from sqlalchemy import create_engine, text        # DB-Verbindung + rohes SQL

FILENAME = "Lets Meet DB Dump.xlsx"               # Name der Excel-Quelldatei
HOBBY_COL = "Hobby1 %Prio1%; Hobby2 %Prio2%; Hobby3 %Prio3%; Hobby4 %Prio4%; Hobby5 %Prio5%;"   # exakter Spaltenname
HOBBY_PATTERN = re.compile(r"([^%;]+?)\s*%(\d+)%\s*;?")   # Gruppe 1 = Hobbyname, Gruppe 2 = Prioritaet
TRENNER = ", "                                    # Trennzeichen fuer Name und Adresse

DB_URL = "postgresql+psycopg2://user:secret@localhost:5432/lf8_lets_meet_db"   # Ziel-Datenbank
MONGO_URL = "mongodb://localhost:27017"           # MongoDB-Server
MONGO_DB = "lets_meet"                            # MongoDB-Datenbank
MONGO_COLL = "users"                              # MongoDB-Collection

try:
    SCRIPT_DIR = Path(__file__).resolve().parent  # Ordner der Skriptdatei
except NameError:
    SCRIPT_DIR = Path.cwd()                       # Fallback fuer Notebook/REPL

def leer_zu_none(wert):
    """'' und reine Leerzeichen zu None -> sonst greift COALESCE nicht."""
    if wert is None:                              # schon None -> nichts zu tun
        return None
    s = str(wert).strip()                         # in Text wandeln, Rand-Leerzeichen weg
    return s if s else None                       # leerer Rest wird zu None


def norm_email(wert):
    """E-Mail vereinheitlichen: klein + getrimmt. Basis fuer das Matching."""
    s = leer_zu_none(wert)                        # erst die normale Leer-Behandlung
    return s.lower() if s else None               # dann konsequent kleinschreiben


def section(titel):
    print("\n" + "=" * 70)                        # Leerzeile + Trennlinie
    print(titel)                                  # Abschnitts-Ueberschrift
    print("=" * 70)                               # Trennlinie darunter


def finde_xlsx(dateiname=FILENAME):
    kandidaten = [                                # wahrscheinliche Speicherorte
        SCRIPT_DIR / dateiname, SCRIPT_DIR.parent / dateiname,   # neben dem Skript / darueber
        Path.cwd() / dateiname, Path.home() / dateiname,         # Arbeitsverzeichnis / Home
        Path.home() / "work" / dateiname,                        # ~/work
    ]
    for pfad in kandidaten:                       # Kandidaten der Reihe nach pruefen
        if pfad.exists():                         # erste existierende Datei gewinnt
            return pfad
    treffer = list(Path.home().rglob(dateiname))  # Notfall: Home rekursiv durchsuchen
    if treffer:
        return treffer[0]                         # ersten Treffer nehmen
    raise FileNotFoundError(f"'{dateiname}' nicht gefunden.")   # sonst sauber abbrechen

def erstelle_schema(engine):
    with engine.begin() as conn:                  # Transaktion, am Ende COMMIT
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS ort (
                ort_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- ID von PostgreSQL
                plz    TEXT NOT NULL,                                         -- PLZ als Text
                stadt  TEXT NOT NULL,                                         -- Ortsname
                UNIQUE (plz, stadt)                                           -- verhindert Ort-Dubletten
            )"""))
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS hobby (
                hobby_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- ID von PostgreSQL
                name     TEXT NOT NULL UNIQUE                                    -- verhindert Hobby-Dubletten
            )"""))
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS person (
                person_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- ID von PostgreSQL
                imp             TEXT    NOT NULL,        -- Quelle, die den Satz angelegt hat
                install         INTEGER NOT NULL,        -- laufende Nummer je Quelle
                nachname        TEXT    NOT NULL,        -- Pflichtfeld der View
                vorname         TEXT    NOT NULL,        -- Pflichtfeld der View
                geschlecht      TEXT,                    -- optional, wird ggf. ergaenzt
                interessiert_an TEXT,                    -- optional, wird ggf. ergaenzt
                geburtsdatum    DATE    NOT NULL,        -- Pflichtfeld der View
                ort_id          INTEGER NOT NULL REFERENCES ort(ort_id),   -- FK auf ort
                UNIQUE (imp, install)                    -- natuerlicher Schluessel zur Quelle
            )"""))
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS kontakt (
                kontakt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- ID von PostgreSQL
                person_id  INTEGER NOT NULL UNIQUE REFERENCES person(person_id),      -- UNIQUE = 1:1 zu person
                email      TEXT    NOT NULL UNIQUE,      -- harte Dublettensperre + Matching-Feld
                strasse_nr TEXT,                         -- optional, wird ggf. ergaenzt
                telefon    TEXT                          -- optional, wird ggf. ergaenzt
            )"""))
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS person_hobby (
                person_id  INTEGER NOT NULL REFERENCES person(person_id),   -- FK auf person
                hobby_id   INTEGER NOT NULL REFERENCES hobby(hobby_id),     -- FK auf hobby
                prioritaet INTEGER,                                         -- Rang 1..5, optional
                PRIMARY KEY (person_id, hobby_id)                           -- jedes Hobby je Person nur einmal
            )"""))
        conn.execute(text("""
            CREATE OR REPLACE VIEW migration_users AS     -- REPLACE = beliebig oft ausfuehrbar
            SELECT k.email AS email, p.vorname AS first_name,      -- Zielfeldnamen englisch
                   p.nachname AS last_name, p.geburtsdatum AS birth_date,
                   o.plz AS postal_code, o.stadt AS city
            FROM person p
            JOIN ort o     ON p.ort_id    = o.ort_id      -- Ort je Person
            JOIN kontakt k ON k.person_id = p.person_id   -- Kontaktdaten je Person
        """))
    print("Schema geprueft/angelegt.")             # Statusmeldung

def lade_excel():
    df = pd.read_excel(finde_xlsx(), dtype=str, keep_default_na=False)   # alles als Text, leere Zellen = ""

    name = df["Nachname, Vorname"].str.split(TRENNER, n=1, expand=True)  # 1 Split -> 2 Spalten
    adr = df["Straße Nr, PLZ Ort"].str.split(TRENNER, n=2, expand=True)  # 2 Splits -> 3 Spalten

    parsed = df[HOBBY_COL].apply(                          # je Zeile Liste aus (Hobby, Prio)
        lambda t: HOBBY_PATTERN.findall(t) if isinstance(t, str) else [])

    out = pd.DataFrame({
        "nachname":        name[0].map(leer_zu_none),      # Teil vor dem Komma
        "vorname":         name[1].map(leer_zu_none),      # Teil nach dem Komma
        "email":           df["E-Mail"].map(norm_email),   # normalisiert -> Matching-Schluessel
        "strasse_nr":      adr[0].map(leer_zu_none),       # "Musterweg 12"
        "telefon":         df["Telefon"].map(leer_zu_none),                    # Telefonnummer
        "geschlecht":      df["Geschlecht (m/w/nonbinary)"].map(leer_zu_none), # m/w/nonbinary
        "interessiert_an": df["Interessiert an"].map(leer_zu_none),            # Praeferenz
        "plz":             adr[1].map(leer_zu_none),       # Postleitzahl
        "stadt":           adr[2].map(leer_zu_none),       # Ortsname
        "geburtsdatum":    pd.to_datetime(df["Geburtsdatum"],      # deutsches Datumsformat
                                          format="%d.%m.%Y",
                                          errors="coerce").dt.date,   # ungueltig -> NaT
    })
    out["hobbys"] = parsed.apply(                          # Rohtreffer in Tupel-Liste wandeln
        lambda p: [(h.strip(), int(prio)) for h, prio in p])
    return out                                             # einheitliches Format zurueck


def lade_mongodb():
    """ACHTUNG: Feldnamen an die eigene Collection anpassen (findOne() ansehen)."""
    from pymongo import MongoClient                        # Import lokal: nur noetig, wenn genutzt

    docs = list(MongoClient(MONGO_URL)[MONGO_DB][MONGO_COLL].find({}))   # alle Dokumente holen
    zeilen = []                                            # Sammelliste
    for d in docs:                                         # jedes Dokument umformen
        zeilen.append({
            "nachname":        leer_zu_none(d.get("last_name")),       # .get() = kein KeyError
            "vorname":         leer_zu_none(d.get("first_name")),      # bei fehlendem Feld
            "email":           norm_email(d.get("email")),             # gleiche Normalisierung wie Excel
            "strasse_nr":      leer_zu_none(d.get("street")),          # Strasse + Hausnummer
            "telefon":         leer_zu_none(d.get("phone")),           # Telefonnummer
            "geschlecht":      leer_zu_none(d.get("gender")),          # Geschlecht
            "interessiert_an": leer_zu_none(d.get("interested_in")),   # Praeferenz
            "plz":             leer_zu_none(d.get("postal_code")),     # Postleitzahl
            "stadt":           leer_zu_none(d.get("city")),            # Ortsname
            "geburtsdatum":    pd.to_datetime(d.get("birth_date"),     # Format wird geraten
                                              errors="coerce").date()
                               if d.get("birth_date") else None,       # Feld fehlt -> None
            "hobbys":          [(h, None) for h in d.get("hobbies", [])],   # Mongo hat keine Prios
        })
    return pd.DataFrame(zeilen)                            # einheitliches Format zurueck

def importiere(engine, df, quelle):
    section(f"Import Quelle '{quelle}' ({len(df)} Rohzeilen)")

    df = df.copy().reset_index(drop=True)          # Original nicht veraendern, Index normalisieren

    pflicht = ["email", "nachname", "vorname", "geburtsdatum", "plz", "stadt"]   # NOT-NULL-Felder
    unvollstaendig = df[pflicht].isna().any(axis=1)        # Zeilen mit Luecke markieren
    if unvollstaendig.any():                               # wenn es welche gibt
        print(f"  {unvollstaendig.sum()} Zeilen ohne Pflichtfeld -> uebersprungen")
        df = df[~unvollstaendig]                           # aussortieren statt am NOT NULL zu scheitern

    vor = len(df)                                          # Zeilenzahl merken
    df = df.drop_duplicates(subset="email", keep="first")  # Dubletten INNERHALB der Quelle
    if vor != len(df):                                     # wenn welche entfernt wurden
        print(f"  {vor - len(df)} quellinterne E-Mail-Dubletten entfernt")

    if df.empty:                                           # nichts uebrig
        print("  Nichts zu importieren.")
        return                                             # frueh aussteigen

    with engine.begin() as conn:                           # eine Transaktion fuer den ganzen Import

        for plz, stadt in df[["plz", "stadt"]].drop_duplicates().itertuples(index=False):
            conn.execute(text("INSERT INTO ort (plz, stadt) VALUES (:p, :s) "
                              "ON CONFLICT (plz, stadt) DO NOTHING"),   # existiert schon -> ignorieren
                         {"p": plz, "s": stadt})

        namen = {h for liste in df["hobbys"] for h, _ in liste if h}    # alle Hobbynamen der Quelle
        for n in namen:                                                 # Menge = schon dublettenfrei
            conn.execute(text("INSERT INTO hobby (name) VALUES (:n) "
                              "ON CONFLICT (name) DO NOTHING"), {"n": n})   # Dublette -> ignorieren

        ort_lookup = {(r[1], r[2]): r[0] for r in                       # (plz, stadt) -> ort_id
                      conn.execute(text("SELECT ort_id, plz, stadt FROM ort"))}
        hobby_lookup = {r[1]: r[0] for r in                             # name -> hobby_id
                        conn.execute(text("SELECT hobby_id, name FROM hobby"))}
        bekannt = {r[0]: r[1] for r in                                  # email -> person_id (Bestand)
                   conn.execute(text("SELECT email, person_id FROM kontakt"))}

        neu = df[~df["email"].isin(bekannt)]               # E-Mail unbekannt -> neue Person
        alt = df[df["email"].isin(bekannt)]                # E-Mail bekannt   -> nur ergaenzen
        print(f"  {len(neu)} neue Personen, {len(alt)} bereits vorhanden")

        offset = conn.execute(text(
            "SELECT COALESCE(MAX(install), 0) FROM person WHERE imp = :q"),   # 0 beim ersten Lauf
            {"q": quelle}).scalar()
        print(f"  install startet bei {offset + 1}")       # beim ersten Lauf also bei 1

        for i, r in enumerate(neu.itertuples(), start=1):  # zeilenweise, damit RETURNING nutzbar ist
            pid = conn.execute(text("""
                INSERT INTO person (imp, install, nachname, vorname, geschlecht,
                                    interessiert_an, geburtsdatum, ort_id)
                VALUES (:imp, :install, :nachname, :vorname, :geschlecht,
                        :interessiert_an, :geburtsdatum, :ort_id)
                RETURNING person_id
            """), {                                        # RETURNING liefert die frische ID direkt
                "imp": quelle,                             # Quellenkennzeichen
                "install": offset + i,                     # fortlaufende Nummer
                "nachname": r.nachname, "vorname": r.vorname,
                "geschlecht": r.geschlecht, "interessiert_an": r.interessiert_an,
                "geburtsdatum": r.geburtsdatum,
                "ort_id": ort_lookup[(r.plz, r.stadt)],    # FK per Lookup aufloesen
            }).scalar_one()                                # genau ein Wert erwartet

            conn.execute(text("""
                INSERT INTO kontakt (person_id, email, strasse_nr, telefon)
                VALUES (:pid, :email, :strasse_nr, :telefon)
            """), {"pid": pid, "email": r.email,           # kein ON CONFLICT noetig:
                   "strasse_nr": r.strasse_nr,             # die E-Mail war nachweislich neu
                   "telefon": r.telefon})

            bekannt[r.email] = pid                         # Lookup fuer den Hobby-Teil ergaenzen

        for r in alt.itertuples():                         # nur auffuellen, nie ueberschreiben
            pid = bekannt[r.email]                         # person_id aus dem Bestand
            conn.execute(text("""
                UPDATE person SET
                    geschlecht      = COALESCE(geschlecht, :g),    -- NULL -> neuer Wert, sonst unveraendert
                    interessiert_an = COALESCE(interessiert_an, :i)
                WHERE person_id = :pid
            """), {"g": r.geschlecht, "i": r.interessiert_an, "pid": pid})
            conn.execute(text("""
                UPDATE kontakt SET
                    strasse_nr = COALESCE(strasse_nr, :s),         -- gleiche Logik fuer Kontaktdaten
                    telefon    = COALESCE(telefon, :t)
                WHERE person_id = :pid
            """), {"s": r.strasse_nr, "t": r.telefon, "pid": pid})

        zuordnungen = []                                   # Sammelliste
        for r in df.itertuples():                          # neue und bekannte Personen
            pid = bekannt.get(r.email)                     # person_id nachschlagen
            if pid is None:                                # sollte nicht vorkommen
                continue                                   # sicherheitshalber ueberspringen
            for name_h, prio in r.hobbys:                  # alle Hobbys der Zeile
                if name_h in hobby_lookup:                 # nur bekannte Namen
                    zuordnungen.append({"pid": pid,
                                        "hid": hobby_lookup[name_h],
                                        "prio": prio})
        if zuordnungen:                                    # nur wenn es etwas gibt
            conn.execute(text("""
                INSERT INTO person_hobby (person_id, hobby_id, prioritaet)
                VALUES (:pid, :hid, :prio)
                ON CONFLICT (person_id, hobby_id) DO NOTHING   -- Zuordnung existiert -> ignorieren
            """), zuordnungen)
        print(f"  {len(zuordnungen)} Hobby-Zuordnungen verarbeitet")

def kontrolle(engine):
    section("Kontrolle")
    with engine.connect() as conn:                         # nur lesend
        for t in ["ort", "hobby", "person", "kontakt", "person_hobby"]:
            n = conn.execute(text(f"SELECT COUNT(*) FROM {t}")).scalar()   # Zeilen zaehlen
            print(f"  {t}: {n} Zeilen")                    # Ergebnis ausgeben

        print("\n  Personen je Quelle:")                   # zeigt, was welcher Lauf angelegt hat
        for imp, n in conn.execute(text(
                "SELECT imp, COUNT(*) FROM person GROUP BY imp ORDER BY imp")):
            print(f"    {imp}: {n}")

        n_view = conn.execute(text("SELECT COUNT(*) FROM migration_users")).scalar()   # Zeilen der View
        n_mail = conn.execute(text(
            "SELECT COUNT(DISTINCT email) FROM migration_users")).scalar()             # eindeutige E-Mails
        print(f"\n  migration_users: {n_view} Zeilen, {n_mail} eindeutige E-Mails")
        if n_view != n_mail:                               # beide Zahlen muessen gleich sein
            print("  WARNUNG: E-Mail-Dubletten in der View!")

        waisen = conn.execute(text("""
            SELECT COUNT(*) FROM person p                      -- Person ohne Kontaktsatz waere das
            LEFT JOIN kontakt k ON k.person_id = p.person_id   -- Zeichen eines Abbruchs mitten drin
            WHERE k.person_id IS NULL
        """)).scalar()
        print(f"  Personen ohne Kontaktsatz: {waisen}")    # sollte immer 0 sein


def main():
    engine = create_engine(DB_URL)                 # Verbindung aufbauen
    erstelle_schema(engine)                        # Schema sicherstellen
    importiere(engine, lade_excel(), "Excel")      # 1. Quelle
    importiere(engine, lade_mongodb(), "MongoDB")  # 2. Quelle, ergaenzt die erste
    kontrolle(engine)                              # Ergebnis pruefen


if __name__ == "__main__":     # nur bei direktem Aufruf, nicht beim Import
    main()                     # Programm starten
